---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    author: intelliqit
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30008
  selector:
    type: ci-cd
...
