---
apiVersion: v1
kind: Service
metadata:
  name: server-abc
  labels:
    author: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    author: intelliqit
    type: db
...
